// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmrghznhrrmxnlwihbof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imttcmdoem5ocnJteG5sd2loYm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTg3ODYsImV4cCI6MjA2ODE3NDc4Nn0.enASwXL-IlwqTVPyoklh-EZQxl0whnv_PIHBSu5nB28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});